### ISSUE TITLE
Streaming Results to File

### ISSUE THREAD

**Issue by codingo** [Ice3man543/subfinder#40]
Some scans using a domain list can take a very long time to run - if the connection drops our or the application crashes during a scan this can lead to some very frustrating results.

It would be good to have results stream to the output file as they are discovered instead of writing at the duration of the scan to help prevent these scenarios causing a loss of results.

**Comment by codingo** [comment]
This can be done currently with a hack by doing:

```
./main -dl ~/Documents/largebountylist.txt -silent > ~/Documents/largesubdomainlist.txt
```

And then using tail -f on the source file, for example:

```
tail -f ~/Documents/largesubdomainlist.txt
```

This will likely be native in the future but this is the workaround for now.

**Comment by C-Sto** [comment]
Using the list option with an output file should accomplish this - at this stage it overwrites the output file every time a domain is complete. 

I'm unable to test at the moment, but I think changing the open mode to 'create if not there, otherwise append' should give the desired behaviour at the completion of each domain. Won't stream as individual subs are found, though.

replace this line:
https://github.com/Ice3man543/subfinder/blob/master/libsubfinder/output/output.go#L23
with
>   file, err := os.OpenFile(state.Output, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)

**Comment by Ice3man543** [comment]
Yep @C-Sto I've had that solution from some time. But only that will not solve the problem. We'd have to write each subdomain found to file at the same time it is found. We'd need a way of tracking the duplicates by maintaining a global array of subdomains found and then comparing whether the subdomain found is already in array, and if not write it to the output :+1: 
Needs some work :)

**Comment by Ice3man543** [comment]
@codingo Done. Tell me what you think?

**Comment by codingo** [comment]
Looks like a good change, closing this issue as looks largely resolved.
